name: Loom CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  test:
    name: Tests (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.13", "3.11" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema

      - name: Sanity tree
        run: |
          pwd
          printf "\n--- root ---\n"; ls -la || true
          for d in agents agents/loomweaver scripts src .github/workflows; do
            printf "\n--- %s ---\n" "$d"
            if [ -d "$d" ]; then ls -la "$d"; else echo "missing"; fi
          done

      # Build to a temp bundle (for smoke only). Do NOT overwrite canonical AST.
      - name: Compile (temp bundle)
        run: |
          python -m src.compiler \
            agents/loomweaver/loomweaver.outline.md \
            agents/loomweaver/loomweaver.modules.ast.build.json
          ls -la agents/loomweaver/*.json || true

      # ✅ Validate the committed canonical AST (avoids '<anonymous>' placeholders)
      - name: Validate (canonical AST)
        run: |
          python scripts/validate_program.py \
            --modules agents/loomweaver/loomweaver.modules.ast.json \
            --strict

      # ✅ Tests use canonical AST + compare receipts to goldens
      - name: Tests (strict; value + receipts)
        run: |
          python scripts/run_module_tests.py \
            --modules agents/loomweaver/loomweaver.modules.ast.json \
            --tests   agents/loomweaver/loomweaver.tests.json \
            --strict

  enforce_capabilities:
    name: Capability Enforcement Smoke (py3.13)
    runs-on: ubuntu-latest
    needs: [ test ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          check-latest: true

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema

      - name: Compile (temp bundle)
        run: |
          python -m src.compiler \
            agents/loomweaver/loomweaver.outline.md \
            agents/loomweaver/loomweaver.modules.ast.build.json

      - name: Validate (canonical AST)
        run: |
          python scripts/validate_program.py \
            --modules agents/loomweaver/loomweaver.modules.ast.json \
            --strict

      - name: Enforced VM smoke
        run: |
          python scripts/loom.cli.py run "Greeting Module" name=Alice --enforce-capabilities
