name: Loom CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  test:
    name: Tests (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13", "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install jsonschema
          fi

      - name: Sanity tree
        run: |
          pwd
          printf "\n--- root ---\n"; ls -la || true
          for d in "agents" "agents/loomweaver" "scripts" "src"; do
            printf "\n--- %s ---\n" "$d"
            if [ -d "$d" ]; then ls -la "$d"; else echo "missing"; fi
          done

      - name: Compile (skip if no compiler)
        run: |
          if [ -f src/compiler.py ]; then
            echo "Compiler present: running compile"
            python scripts/loom.cli.py compile
          else
            echo "No src/compiler.py found; skipping compile"
          fi

      - name: Validate (errors only)
        run: |
          python scripts/loom.cli.py validate --strict

      - name: Tests (strict; compare receipts to goldens)
        run: |
          python scripts/loom.cli.py test --strict

  enforce_capabilities:
    name: Capability Enforcement Smoke (py3.13)
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          check-latest: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install jsonschema
          fi

      - name: Compile (skip if no compiler)
        run: |
          if [ -f src/compiler.py ]; then
            python scripts/loom.cli.py compile
          else
            echo "No compiler; skipping"
          fi

      - name: Validate
        run: |
          python scripts/loom.cli.py validate --strict

      - name: Enforced VM smoke
        run: |
          python scripts/loom.cli.py run "Greeting Module" name=Alice --enforce-capabilities
